
version: 2

models:
  - name: int_rental
    description: "precursor to fact"
    columns:
        - name: rental_id
          description: "Main business key"
          data_tests:
              - unique
              - not_null
        - name: inventory_id
          data_tests:
            - fast_distinct_check:
                arguments: 
                  target_count: 1194

  - name: top_customers
    columns:
      - name: customer_id
      - name: customer_name
      - name: customers.birth_year
      - name: total_rental_amount
      - name: customer_rank

sources:
  - name: landing
    tables:
      - name: store
        columns:
          - name: store_id
            data_tests:
              - unique
              - not_null
      - name: address
        columns:
          - name: address_id
            data_tests:
              - unique
              - not_null
      - name: customer
        columns:
          - name: customer_id
            data_tests:
              - unique
              - not_null
      - name: payment
        columns:
          - name: payment_id
            data_tests:
              - unique
              - not_null
          # Business says each payment is for 1 rental
          - name: rental_id
            data_tests:
              - unique
              - not_null
      - name: staff
        columns:
          - name: staff_id
            data_tests:
              - unique
              - not_null
      - name: country
        columns:
          - name: country_id
            data_tests:
              - unique
              - not_null
      - name: car
        columns:
          - name: car_id
            data_tests:
              - unique
              - not_null
      - name: inventory
        columns:
          - name: inventory_id
            data_tests:
              - unique
              - not_null
      - name: rental
        columns:
          - name: rental_id
            data_tests:
              - unique
              - not_null
      - name: equipment
        columns:
          - name: equipment_id
            data_tests:
              - unique
              - not_null
      - name: city
        columns:
          - name: city_id
            data_tests:
              - unique
              - not_null
      - name: inventory_equipment
      
unit_tests:
  - name: test_top_customers_looks_at_amounts_not_row_count
    description: "We can't afford to **not** see our top clients"
    model: top_customers
    given:
      - input: ref('stg_customer')
        rows:
          - {customer_id: 1, first_name: John, last_name: Doe}
          - {customer_id: 2, first_name: John, last_name: Doe}
          - {customer_id: 3, first_name: John, last_name: Doe}
          - {customer_id: 4, first_name: John, last_name: Doe}
          - {customer_id: 5, first_name: John, last_name: Doe}
          - {customer_id: 6, first_name: John, last_name: Doe}
          - {customer_id: 7, first_name: John, last_name: Doe}
          - {customer_id: 8, first_name: John, last_name: Doe}
          - {customer_id: 9, first_name: John, last_name: Doe}
          - {customer_id: 10, first_name: John, last_name: Doe}
          - {customer_id: 11, first_name: John, last_name: Doe}
          - {customer_id: 12, first_name: John, last_name: Doe}

      - input: ref('int_rental')
        rows:
          - {customer_id: 1, rental_amount: 100}
          - {customer_id: 2, rental_amount: 100}
          - {customer_id: 3, rental_amount: 21}
          - {customer_id: 4, rental_amount: 20}
          - {customer_id: 5, rental_amount: 19}
          - {customer_id: 6, rental_amount: 18}
          - {customer_id: 7, rental_amount: 17}
          - {customer_id: 8, rental_amount: 16}
          - {customer_id: 9, rental_amount: 15}
          - {customer_id: 10, rental_amount: 14}
          - {customer_id: 11, rental_amount: 13}
          - {customer_id: 12, rental_amount: 12}
    expect:
      rows:
        - {customer_id: 1, total_rental_amount: 100}
        - {customer_id: 2, total_rental_amount: 100}
        - {customer_id: 3, total_rental_amount: 21}
        - {customer_id: 4, total_rental_amount: 20}
        - {customer_id: 5, total_rental_amount: 19}
        - {customer_id: 6, total_rental_amount: 18}
        - {customer_id: 7, total_rental_amount: 17}
        - {customer_id: 8, total_rental_amount: 16}
        - {customer_id: 9, total_rental_amount: 15}
        - {customer_id: 10, total_rental_amount: 14}
        - {customer_id: 11, total_rental_amount: 13}
